package monitor_test

const (
	testFlagTheme       = "-theme"
	testCPUName         = "AMD Ryzen 5 5600X 6-Core Processor"
	testDataMount       = "/mnt/data"
	testDiskDevice      = "sdd"
	testDiskSource      = "/dev/sdd"
	testExampleHost     = "example-host"
	testFFmpegCommand   = "ffmpeg"
	testFSLabelPrefix   = "FS "
	testGPUName         = "NVIDIA GeForce RTX 3060"
	testGPUUUID         = "GPU-123"
	testGPUUUIDZero     = "GPU-0"
	testGPU0Decoder     = "GPU0 Decoder"
	testGPU0Encoder     = "GPU0 Encoder"
	testGPU0Fan         = "GPU0 Fan"
	testGPU0Graphics    = "GPU0 Graphics"
	testGPU0Load        = "GPU0 Load"
	testGPU0PCIe        = "GPU0 PCIe"
	testGPU0PState      = "GPU0 PState"
	testGPU0SM          = "GPU0 SM"
	testGPU0Temp        = "GPU0 Temp"
	testGPU0Throttle    = "GPU0 Throttle"
	testGPU0Video       = "GPU0 Video"
	testHost            = "gpu-wsl"
	testIfaceEth0       = "eth0"
	testIfaceTailscale  = "tailscale0"
	testPythonCommand   = "python"
	testRemoteName      = "DESKTOP-63C6KR5"
	testRemoteTimestamp = "2026-05-28 20:22:58"
	testThreeGiB        = "3.0 GiB"
)
